Put prefixPath in config.devServer.devMiddleware.publicPath
After updating from webpack-dev-server v3. -> v.4 the configuration
config.devServer.publicPath is now:

config.devServer.devMiddleware.publicPath

See:

https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md#-breaking-changes

Avoid error:

ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.