Remove mini-css-extract-plugin from peerDependencies
When using pnpm 9, and having mini-css-extract-plugin as a peerDependencie, it causes an error in the Volto build:

    Error: You forgot to add 'mini-css-extract-plugin' plugin

The cookieplone job still uses pnpm 9. Therefore, we cannot have it as a peerDependencie for now.