Fix error and rename test to "should save typed content in the Slate editor"
Use `cy.getSlateEditorAndType` in test.  The previous name didn't reflect what the test did. So it was renamed.

This fix:

  1) Block Tests
       should create 4 slate blocks, first 3 with mouse, the last with an Enter in the third block:
     AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Hello Slate World' but never did.
      at Context.eval (webpack://@plone/volto/./cypress/tests/core/volto-slate/02-block-slate.js:13:7)