build(version): Fix version constraint conflicts
These popped up after merging master.  The conflicting version messages in order
encountered are:

    Version and requirements information containing plone.app.vocabularies:
      [versions] constraint on plone.app.vocabularies: 4.3.0 # plone.volto requires it
      Requirement of plone.volto: plone.app.vocabularies>=4.3.0
    While:
      Updating instance.
    Error: The requirement ('plone.app.vocabularies>=4.3.0') is not allowed by your
    [versions] constraint (4.3.0 # plone.volto requires it)

then:

    Version and requirements information containing plone.restapi:
      [versions] constraint on plone.restapi: 8.16.2 # force to latest p.restapi
      Requirement of plone.volto: plone.restapi>=8.13.0
      Requirement of Plone==5.2.6: plone.restapi
    While:
      Installing instance.
    Error: The requirement ('plone.restapi>=8.13.0') is not allowed by your [versions] constraint (8.16.2 # force to latest p.restapi)

then:

    Version and requirements information containing plone.rest:
      [versions] constraint on plone.rest: 2.0.0a1 # new JSON only traversal
      Requirement of plone.volto: plone.restapi>=8.13.0
      Requirement of Plone==5.2.6: plone.restapi
      Requirement of plone.restapi>=8.13.0: setuptools
      Requirement of plone.restapi>=8.13.0: pytz
      Requirement of plone.restapi>=8.13.0: python-dateutil
      Requirement of plone.restapi>=8.13.0: plone.schema>=1.2.1
      Requirement of plone.restapi>=8.13.0: plone.rest>=1.0a6
      Requirement of plone.restapi>=8.13.0: plone.behavior>=1.1
      Requirement of plone.restapi>=8.13.0: PyJWT
    While:
      Installing instance.
    Error: The requirement ('plone.rest>=1.0a6') is not allowed by your [versions] constraint (2.0.0a1 # new JSON only traversal)