Fixes Cypress "Index Text Block" test
Wait for the search field to be enabled before trying to enter
something.

Fix the error:

1) Block Indexing Tests
       Index Text Block:
     CypressError: `cy.type()` failed because it targeted a disabled
element.